/**
 * Site content. Plain globals so the site runs from file:// without a build
 * step or fetch(). Edit here to update the portfolio — markup stays untouched.
 */

const PROFILE = {
  name: 'Jakub Pawlina',
  tagline: 'Solving Problems, Building Ideas — Where Tech Meets Vision',
  role: 'Test Automation Developer · IoT tester · builder',
  location: 'Kraków, Poland',
  company: 'Geotab',
  email: 'jakub@jakubpawlina.com',
  emailAlt: 'jakub.pawlina@outlook.com',
  phone: '+48 789 429 545',
  github: 'https://github.com/jakubpawlina',
  linkedin: 'https://www.linkedin.com/in/jakub-pawlina/',
  notes: 'https://notes.jakubpawlina.com/',
  orcid: '0009-0006-1387-4606',
  pgp: 'https://keys.mailvelope.com/pks/lookup?op=get&search=jakub%40jakubpawlina.com',
  cv: 'assets/cv-jakub-pawlina.pdf',
};

const STATS = [
  { value: '9', label: 'years building' },
  { value: '100+', label: 'projects built' },
  { value: '75+', label: 'GitHub followers' },
  { value: '∞', label: 'bugs found & squashed' },
];

const SKILLS = [
  'Python', 'Selenium', 'Behave / BDD', 'IoT', 'CI/CD', 'C++', 'Java',
  'PHP', 'SQL', 'Solana', 'ZKP', 'Cybersecurity', 'Product Design',
];

const EXPERIENCE = [
  {
    role: 'Test Automation Developer',
    org: 'Geotab',
    date: 'now · full-time',
    desc: 'End-to-end preparation and evolution of complex test environments for connected systems and new product validation — combining hardware setup, test framework development, system-level testing, CI/CD integration, and tooling for analysis and reporting.',
  },
  {
    role: 'IoT Test Engineer',
    org: 'Aptiv Connected Services',
    date: 'internship',
    desc: 'Part of the IoT testing team: web application testing and validation of physical IoT devices, designing and executing test cases, and automating tests with Selenium, Python and Behave. Improved CI/CD pipelines (GitHub Actions, custom tooling) and proposed process optimizations that raised team efficiency.',
  },
  {
    role: 'MSc Applied Computer Science',
    org: 'DSW Ideis University',
    date: 'in progress',
    desc: 'Pursued alongside full-time work, deepening applied software engineering, systems and security.',
  },
  {
    role: 'BSc Computer Science',
    org: 'AGH University of Science and Technology',
    date: 'graduated',
    desc: 'Technical foundation across software engineering, algorithms, systems, data processing and security.',
  },
  {
    role: 'Builder / Freelance Projects',
    org: 'Client websites, tools and experiments',
    date: 'ongoing',
    desc: 'Websites, CMS systems, APIs, desktop apps, educational tools, technical templates and security/AI experiments.',
  },
];

// image: optional thumbnail in img/ shown in the detail modal.
// links: only verified, owned URLs — an empty array simply renders no link buttons.
const PROJECTS = [
  {
    title: 'GPS Reference Module',
    category: 'Embedded / IoT',
    featured: true,
    image: null,
    summary: 'Self-contained GPS reference station for local test and measurement networks.',
    description: 'A self-contained GPS reference station for local test and measurement networks, built around an ESP32. Prototyped and simulated with Wokwi, it provides a stable positioning reference for benchmarking and validating other devices.',
    tech: ['Python', 'ESP32', 'GPS', 'Wokwi', 'IoT'],
    links: [{ label: 'source code', url: 'https://github.com/jakubpawlina/GPS-reference-module' }],
    detail: 'Recent hardware/IoT work that maps directly to test, measurement and connected-device engineering.',
  },
  {
    title: 'Digital Identity System',
    category: 'Blockchain / ZKP',
    featured: true,
    image: 'img/blockchain.png',
    summary: 'Privacy-preserving digital identity platform using blockchain and Zero-Knowledge Proofs.',
    description: 'A blockchain-based identity platform that uses Zero-Knowledge Proofs to let users prove selected attributes, such as being over 18, without revealing sensitive personal data like an exact birth date. Built around decentralized identity principles to stay secure, privacy-preserving and interoperable.',
    tech: ['Solana', 'ZKP', 'DID', 'Privacy'],
    links: [
      { label: 'source code', url: 'https://github.com/bsc-digital-identity/digital-identity-system' },
      { label: 'organization', url: 'https://github.com/bsc-digital-identity' },
    ],
    detail: 'A flagship item: privacy, blockchain, identity systems and a real-world verification use case rather than a simple demo.',
  },
  {
    title: 'Sumo Championship Manager',
    category: 'Sports management app',
    featured: true,
    image: 'img/sumochampionshipmanager.png',
    summary: 'System for managing sumo championships for the European Sumo Federation.',
    description: 'Application for managing sumo championships for the European Sumo Federation, created during a Software Engineering course at AGH. A full team project with backend, frontend, containerized deployment and defined requirements.',
    tech: ['Java', 'Spring Boot', 'React', 'Docker'],
    links: [{ label: 'source code', url: 'https://github.com/AGH-IO-Antreprenerzy/sumo-championship-manager' }],
    detail: 'Strong team software-engineering project: multi-author delivery, defined requirements and a real client.',
  },
  {
    title: 'Travel Planner API',
    category: 'Backend API',
    featured: true,
    image: 'img/travelplanner.png',
    summary: 'Trip-planning service combining destination info, flights, currency and hotels.',
    description: 'Service for planning trips. It finds information about a destination city, checks possible flights, calculates prices in a selected currency and suggests hotels.',
    tech: ['API', 'Travel', 'Currency', 'Integrations'],
    links: [],
    detail: 'A backend case study that combines multiple external data sources into a single planning flow.',
  },
  {
    title: 'Vocaber',
    category: 'C++ / wxWidgets',
    featured: true,
    image: 'img/vocaber.png',
    summary: 'Desktop app for learning vocabulary and more.',
    description: 'An app for learning vocabulary and definitions, written in C++ with wxWidgets — a learning tool for vocabulary and not only.',
    tech: ['C++', 'wxWidgets', 'CMake'],
    links: [{ label: 'source code', url: 'https://github.com/jakubpawlina/vocaber' }],
    detail: 'Desktop GUI programming, C++ project organization and a concrete personal productivity use case.',
  },
  {
    title: 'Kancelaria Adwokacka Gabriela Pawlina',
    category: 'Client website / IT background',
    featured: true,
    image: 'img/kagp.png',
    summary: 'Website and full IT background for a law firm.',
    description: 'A public website and the complete IT background for a law firm — the public-facing page plus the technical setup and infrastructure around the company presence.',
    tech: ['Website', 'Client work', 'DNS', 'Infrastructure'],
    links: [{ label: 'preview', url: 'https://adwokat.gabrielapawlina.pl/' }],
    detail: 'Practical end-to-end delivery: not just a front page, but a working online presence for a real client.',
  },
  {
    title: 'Kapitan Książka',
    category: 'Client website',
    featured: false,
    image: 'img/kapitanksiazka.png',
    summary: 'Website for an antiquarian bookshop.',
    description: 'A lightweight website for an antiquarian bookshop, focused on clean public presentation and direct access to the offer.',
    tech: ['Website', 'Client work', 'Static'],
    links: [{ label: 'preview', url: 'https://kapitanksiazka.pl' }],
    detail: 'Practical client work with a clear, content-first presentation.',
  },
  {
    title: 'Klich Football School',
    category: 'Client CMS / website',
    featured: false,
    image: 'img/klichfootballschool.png',
    summary: 'Website for a football academy with a CMS built from scratch.',
    description: 'Website for a football school backed by a dedicated content management system built from scratch.',
    tech: ['CMS', 'PHP', 'Website', 'Client work'],
    links: [{ label: 'preview', url: 'https://klichfootballschool.pl' }],
    detail: 'Combines a public website with custom admin and content workflows.',
  },
  {
    title: 'SFI CTF',
    category: 'CTF / security',
    featured: false,
    image: 'img/ctfsfi.png',
    summary: 'Puzzles and application improvements for an academic CTF competition.',
    description: 'Puzzles and improvements of the application for the CTF competition from the SFI Academic Festival.',
    tech: ['CTF', 'Security', 'Web app'],
    links: [{ label: 'preview', url: 'https://ctf.sfi.pl/' }],
    detail: 'A cybersecurity angle that backs the security interest stated in the about section.',
  },
  {
    title: 'Algorithms & Data Structures',
    category: 'C++ reference repo',
    featured: false,
    image: null,
    summary: 'Reference implementations of useful algorithms and data structures in C++.',
    description: 'A growing base of sample implementations of useful algorithms and data structures in C++.',
    tech: ['C++', 'Algorithms', 'Data structures'],
    links: [{ label: 'source code', url: 'https://github.com/jakubpawlina/algorithms-and-data-structures' }],
    detail: 'A technical reference that supports competitive programming and CS fundamentals.',
  },
  {
    title: 'Codeforces Solutions',
    category: 'Competitive programming',
    featured: false,
    image: null,
    summary: 'Solutions to Codeforces programming problems.',
    description: 'A repository with solutions to selected Codeforces problems.',
    tech: ['C++', 'Codeforces', 'Algorithms'],
    links: [
      { label: 'source code', url: 'https://github.com/jakubpawlina/codeforces' },
      { label: 'profile', url: 'https://codeforces.com/submissions/jakubpawlina' },
    ],
    detail: 'Ongoing problem-solving practice and algorithmic discipline.',
  },
  {
    title: 'Testing Solutions',
    category: 'Developer tooling',
    featured: false,
    image: null,
    summary: 'Bash script for testing competitive programming solutions.',
    description: 'A simple Bash script to test solutions for competitive programming tasks.',
    tech: ['Shell', 'Testing', 'CLI'],
    links: [{ label: 'source code', url: 'https://github.com/jakubpawlina/testing-solutions' }],
    detail: 'Small developer tooling tied to the competitive programming workflow.',
  },
  {
    title: 'Gradients Library',
    category: 'UI design utility',
    featured: false,
    image: 'img/gradientslibrary.png',
    summary: 'Gradient library for UI design.',
    description: 'A website with a library of gradients for UI design: pick a gradient, copy its CSS and use it in your project.',
    tech: ['CSS', 'JavaScript', 'UI design'],
    links: [
      { label: 'preview', url: 'https://jakubpawlina.github.io/gradients/' },
      { label: 'source code', url: 'https://github.com/jakubpawlina/gradients' },
    ],
    detail: 'A focused utility that supports product/UI design interest and ships a live preview.',
  },
  {
    title: 'Aygrusha 12 Pro',
    category: 'Landing page',
    featured: false,
    image: 'img/aygrusha.png',
    summary: 'Apple-inspired landing page for a fictional smartphone.',
    description: 'An Apple-inspired landing page for a fictional smartphone, created as a school project for a Russian language lesson.',
    tech: ['HTML', 'CSS', 'Design'],
    links: [
      { label: 'preview', url: 'https://jakubpawlina.github.io/aygrusha/' },
      { label: 'source code', url: 'https://github.com/jakubpawlina/aygrusha' },
    ],
    detail: 'A visual/design exercise: a polished, product-like landing page.',
  },
  {
    title: 'CSS Elements',
    category: 'CSS experiments',
    featured: false,
    image: 'img/csselements.png',
    summary: 'Website elements designed using only CSS.',
    description: 'A collection of website elements designed using only CSS — no images, no JavaScript.',
    tech: ['CSS', 'UI', 'Experiments'],
    links: [{ label: 'preview', url: 'https://jakubpawlina.github.io/css-elements/' }],
    detail: 'A UI craft project for frontend polish and CSS creativity.',
  },
  {
    title: 'Songbook',
    category: 'Static web app',
    featured: false,
    image: 'img/songbook.png',
    summary: 'Responsive online songbook with chords and tabs.',
    description: 'A responsive online songbook with a clean light/dark interface and convenient tab and chord display for guitarists, designed to run as a static website.',
    tech: ['HTML', 'CSS', 'JavaScript'],
    links: [],
    detail: 'Attention to UX with a practical, domain-specific interface for musicians.',
  },
  {
    title: 'Half-online Camp',
    category: 'Scout / interactive website',
    featured: false,
    image: 'img/scoutcamp.png',
    summary: 'Interactive website for a half-online scout camp during COVID-19.',
    description: 'A website for a half-online scout-troop camp that enabled interactive competition during the COVID-19 pandemic.',
    tech: ['Website', 'Scouting', 'Gamification'],
    links: [],
    detail: 'A leadership/community project: technology supporting engagement under remote constraints.',
  },
  {
    title: 'Computation Methods for Science and Technology',
    category: 'Numerical methods',
    featured: false,
    image: 'img/computationalmethods.png',
    summary: 'C++ implementations and visualizations of numerical methods.',
    description: 'C++ implementation, visualization and analysis of interpolation (Lagrange, Newton, Hermite, splines), approximation (polynomial, trigonometric) and equation solving (nonlinear equations, linear systems, Gauss, Thomas and Jacobi methods).',
    tech: ['C++', 'Numerical methods', 'Visualization'],
    links: [],
    detail: 'A substantial academic project spanning algorithms, analysis and numerical computing.',
  },
  {
    title: 'Geometric Algorithms',
    category: 'Python / algorithms',
    featured: false,
    image: 'img/geometricalgorithms.png',
    summary: 'Implementation and analysis of computational geometry algorithms.',
    description: 'Python implementation and analysis of geometric algorithms: point position relative to a line, convex hull, triangulation, segment intersection and Voronoi diagram.',
    tech: ['Python', 'Geometry', 'Algorithms'],
    links: [],
    detail: 'Algorithmic thinking with data visualization and analysis in Python.',
  },
  {
    title: 'Darwin Evolution Simulator',
    category: 'Java / simulation',
    featured: false,
    image: 'img/darwinevolutionsimulator.png',
    summary: 'Evolution simulator written in Java and JavaFX.',
    description: 'An evolution simulator written in Java and JavaFX, modelling organisms, genes and environment over time.',
    tech: ['Java', 'JavaFX', 'Simulation'],
    links: [],
    detail: 'Simulation logic, UI and object-oriented design in one project.',
  },
  {
    title: 'Pneumonia Detection',
    category: 'AI / medical imaging',
    featured: false,
    image: 'img/aipneumonia.png',
    summary: 'AI model for detecting pneumonia from chest X-ray images.',
    description: 'An educational AI model for detecting pneumonia from chest X-ray images.',
    tech: ['AI', 'Computer vision', 'X-ray'],
    links: [],
    detail: 'A portfolio/educational computer-vision model, not a medical product.',
  },
  {
    title: 'Question Answering',
    category: 'AI / NLP',
    featured: false,
    image: 'img/aicontextanswering.png',
    summary: 'AI model for answering questions from a given context.',
    description: 'An AI model for answering questions based on a provided context.',
    tech: ['AI', 'NLP'],
    links: [],
    detail: 'A compact NLP project demonstrating context processing and answer extraction.',
  },
  {
    title: 'Restaurant Database',
    category: 'Database design',
    featured: false,
    image: 'img/restaurantdatabase.png',
    summary: 'Database for managing restaurant orders.',
    description: 'Design and implementation of a database for managing orders in a restaurant.',
    tech: ['SQL', 'Database', 'Design'],
    links: [],
    detail: 'A foundational database-modelling project.',
  },
  {
    title: 'Auto Assurance Base',
    category: 'PHP / database',
    featured: false,
    image: 'img/autoassurancebase.png',
    summary: 'PHP database management system.',
    description: 'A PHP database management system for handling assurance-style records.',
    tech: ['PHP', 'Database', 'CRUD'],
    links: [],
    detail: 'A classic full-stack CRUD project showing fundamentals.',
  },
  {
    title: 'Discord Sender',
    category: 'PHP utility',
    featured: false,
    image: 'img/discordsender.png',
    summary: 'Simple Discord webhook sender.',
    description: 'A webhook sender for Discord, implemented as a simple website in PHP.',
    tech: ['PHP', 'Discord', 'Webhooks'],
    links: [],
    detail: 'A small integration utility showing external service communication.',
  },
  {
    title: 'Notes Front',
    category: 'Blog interface',
    featured: false,
    image: 'img/blogdesign.png',
    summary: 'Base interface for a personal blog, built mostly with CSS.',
    description: 'The base interface for a personal blog, built mostly with CSS. The current notes site continues this writing direction.',
    tech: ['CSS', 'Blog', 'Frontend'],
    links: [{ label: 'notes', url: 'https://notes.jakubpawlina.com/' }],
    detail: 'Connects earlier frontend experiments with the current technical-notes presence.',
  },
  {
    title: 'Rivalry Board',
    category: 'Scout team website',
    featured: false,
    image: 'img/rivalry.png',
    summary: 'Website for tracking rivalry results in a scout team.',
    description: 'A website to track rivalry results within a scout team.',
    tech: ['Website', 'Scouting', 'Competition'],
    links: [],
    detail: 'A small but practical internal tool linking leadership work with software.',
  },
  {
    title: 'ASM Interactive Rectangle',
    category: '8086 Assembly',
    featured: false,
    image: 'img/asmrectangle.png',
    summary: 'Interactive rectangle drawing program in assembly.',
    description: 'An 8086 assembly program for drawing an interactive rectangle with changeable dimensions and color.',
    tech: ['ASM', '8086', 'Graphics'],
    links: [],
    detail: 'Low-level programming: direct control, tight constraints and visual interaction.',
  },
  {
    title: 'ASM Wordy Calculator',
    category: '8086 Assembly',
    featured: false,
    image: 'img/asmcalculator.png',
    summary: 'Basic calculator working on word-based input.',
    description: 'An 8086 assembly calculator that operates on wordy input.',
    tech: ['ASM', '8086', 'Parser'],
    links: [],
    detail: 'Low-level parsing and program flow in a constrained environment.',
  },
  {
    title: 'AGH Report & Slideshow Templates',
    category: 'LaTeX templates',
    featured: false,
    image: 'img/aghreport.png',
    summary: 'LaTeX templates for AGH documents and slides.',
    description: 'LaTeX templates for creating documents and presentations at AGH University of Science and Technology.',
    tech: ['LaTeX', 'Templates'],
    links: [],
    detail: 'Polished productivity tooling for academic work.',
  },
];

// Fallback list — at runtime app.js pulls the latest posts from the live feed
// and replaces these. POST_FEED is the Atom feed it reads.
const POST_FEED = 'https://notes.jakubpawlina.com/feed.xml';
const POSTS = [
  { title: 'Why you should use MFA (and why even this may not be enough)', date: 'May 27, 2024', read: '10 min', url: 'https://notes.jakubpawlina.com/cybersecurity/2024/05/27/why-you-should-use-mfa.html', tag: 'Cybersecurity' },
  { title: 'Optimizing code with vector operations: SSE and AVX', date: 'Apr 9, 2024', read: '10 min', url: 'https://notes.jakubpawlina.com/optimization/2024/04/09/optimizing-code-with-vector-operations-sse-and-avx.html', tag: 'Optimization' },
  { title: 'Unsafe websites. Why HTTP is not enough?', date: 'Dec 15, 2023', read: '11 min', url: 'https://notes.jakubpawlina.com/cybersecurity/2023/12/15/unsafe-websites-why-http-is-not-enough.html', tag: 'Web security' },
  { title: 'Preprocessor — tricks for everyday use', date: 'Jun 26, 2023', read: '5 min', url: 'https://notes.jakubpawlina.com/c%2B%2B/2023/06/26/preprocessor-tricks-for-everyday-use.html', tag: 'C++' },
  { title: 'Amazing CLI tools', date: 'Jun 23, 2023', read: '6 min', url: 'https://notes.jakubpawlina.com/tools/2023/06/23/amazing-cli-tools.html', tag: 'Tools' },
];
